version: '3.1'

services:
  mariadb:
    build:
      context: ../
      dockerfile: ./.docker/Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
    image: mariadb:latest
    restart: always
    ports:
      - ${DB_3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TIMEZONE}
    volumes:
      - ../app/mysql:/var/lib/mysql
      - ../app/backup:/backup
    networks:
      - mariadb_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOST=mariadb
    ports:
      - ${PHPMYADMIN_80}:80
    volumes:
      - ../app/phpmyadmin/sessions:/sessions
    depends_on:
      - mariadb
    networks:
      - mariadb_db

networks:
  mariadb_db:
    name: ${PROJECT_NETWORK}
